version: "3.8"

services:
  db:
    image: postgres:14.11
    container_name: postgres-db-local
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "6543:5432"
    volumes:
      - postgres-data-local:/var/lib/postgresql/data

  app:
    image: jungyeons/zoop_server:latest
    container_name: zoop-app-local
    depends_on:
      - db
    ports:
      - "18080:8080"
    environment:
      PROFILES: local
      ENV: local
      SERVER_NAME: local_server

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass

      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_REDIRECT_URI: http://localhost:18080/users/auth/kakao/callback
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

      FRONT_BASE_URL: ""              # 상대 경로
      FRONT_NICKNAME_PATH: /nickname.html
      FRONT_HOME_PATH: /home.html

  fastapi:
    build:
      context: ./fastapi_service
    container_name: fastapi-local
    depends_on: [db]
    environment:
      # FastAPI 쪽 DB 접속
      DB_URL: postgresql://myuser:mypass@db:5432/mydb
    ports:
      - "8000:8000"




volumes:
  postgres-data-local:
