version: "3.8"

services:
  db:
    image: postgres:14.11
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    volumes:
      - postgres-data:/var/lib/postgresql/data   # 외부 노출 포트 없음 (보안 ↑)

  app:
    image: jungyeons/zoop_server:latest
    container_name: zoop-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      PROFILES: prod
      ENV: prod
      SERVER_NAME: prod_server

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass

      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_REDIRECT_URI: http://43.201.121.201/users/auth/kakao/callback
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

      FRONT_BASE_URL: http://localhost:3000
      FRONT_NICKNAME_PATH: /login/set-nickname
      FRONT_HOME_PATH: /login/complete

  fastapi:
    image: jungyeons/zoop_fastapi:latest   # 서버에 직접 빌드 안 할 경우
    # build:
    #   context: ./fastapi_service        # 이미지를 사전에 빌드·푸시했다면 주석 처리
    container_name: fastapi
    depends_on: [db]
    environment:
      DB_URL: postgresql://myuser:mypass@db:5432/mydb
    # 외부에서 직접 호출하거나 리버스 프록시 할 경우만 포트 노출
    # ports:
    #   - "8000:8000"

volumes:
  postgres-data:
