# 0. 기본 프로필 및 그룹 지정
spring:
  profiles:
    active: ${PROFILES:local}
    group:
      local: local,common
      prod:  prod,common
---

############################
# 1) 공통(common) 영역
############################
spring:
  config:
    activate.on-profile: common

---

############################
# 2) 로컬(local) 프로필
############################
spring:
  config:
    activate.on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:6543/mydb
    username: myuser
    password: mypass
jwt:
  secret: Z6z3q5Lg7FscPqaLfJl5yFjO3PrMnxKfaThgq9e02ZbJY5GgnM0IMK3PMkSzr8lq
kakao:
  client-id: b5cac5dbe8078dd547ed5f7fdd805738
  redirect-uri: http://localhost:8080/users/auth/kakao/callback
server:
  env: local
  name: local_server

## ──⯈ ✨ 로컬 화면경로
front:
  base-url: ""                    # 빈 값이면 상대 경로로 리다이렉트
  nickname-path: "/nickname.html" # 기존 HTML
  home-path: "/home.html"
---

############################
# 3) 운영(prod) 프로필
############################
spring:
  config:
    activate.on-profile: prod
  # …(RDS-URL, SMTP 등 운영 전용 설정)
front:
  base-url: "http://localhost:3000"   # FE 서버(도메인) 기준
  nickname-path: "/login/nicknameForm"
  home-path: "/chat"
