spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: ${POSTGRES_USER:myuser}
    password: ${POSTGRES_PASSWORD:mypass}

  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
