name: CD on main (self-hosted)

on:
  push:
    branches:
      - main            # dev → main 머지, 또는 main에 직접 푸시 시 실행

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      # 0) Docker Hub 로그인 -------------------------------------------
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 1) 코드 동기화 & 컨테이너 재기동 -------------------------------
      - name: Pull & Restart containers
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          set -e

          REPO="FC-DEV3-Final-Project/zoop-backend"
          APP_DIR="/home/ubuntu/zoop-app"
          TOKEN="$GH_PAT"
          BRANCH="main"

          # 1-1) 폴더 초기화 후 main 브랜치 shallow-clone
          rm -rf "$APP_DIR"
          git clone --depth 1 -b "$BRANCH" \
            https://${TOKEN}@github.com/${REPO}.git "$APP_DIR"

          # 1-2) 최신 이미지 pull
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/zoop_server:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/zoop_fastapi:latest

          # 1-3) 기존 컨테이너 종료(볼륨 유지)
          docker compose -f "$APP_DIR/docker-compose.yml" down --remove-orphans || true
          docker rm -f postgres-db zoop-app 2>/dev/null || true

          # 1-4) 재기동
          docker compose -f "$APP_DIR/docker-compose.yml" up -d --pull=never --force-recreate

      # 2) 애플리케이션 워밍업 -----------------------------------------
      - name: Wait for app warm-up
        run: sleep 30      # 필요하면 20~60초 사이로 조정

      # 3) 헬스체크 ----------------------------------------------------
      - name: Health-check 8080
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://localhost:8080/hc      # 스프링 컨트롤러에서 제공하는 /hc
          max-attempts: 60                  # 5초 × 60 = 최대 5분 재시도
          retry-delay: 5s
          follow-redirect: false
          retry-all: false
