name: cd

on:
  workflow_run:
    workflows: ["Maven CI All Checks"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        with:
          host: ${{ secrets.ZOOP_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GH_PAT
          script: |
            set -e

            REPO="FC-DEV3-Final-Project/zoop-backend"
            APP_DIR="/home/ubuntu/zoop-app"
            TOKEN=$GH_PAT

            # 1) 코드 동기화 -------------------------------------------------
            if [ ! -d "$APP_DIR/.git" ]; then
              git clone --depth 1 https://${TOKEN}@github.com/${REPO}.git "$APP_DIR"
            fi
            cd "$APP_DIR"
            git remote set-url origin https://${TOKEN}@github.com/${REPO}.git
            git pull --ff-only origin main

            # 2) 최신 이미지 pull -------------------------------------------
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/zoop_server:latest
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/zoop_fastapi:latest
            # 3) 컨테이너 정리(볼륨 유지) ------------------------------------
            sudo docker compose -f docker-compose.yml down --remove-orphans || true
            sudo docker rm -f postgres-db zoop-app 2>/dev/null || true

            # 4) 재기동 ------------------------------------------------------
            sudo docker compose -f docker-compose.yml up -d --pull=never --force-recreate

      - name: Health-check 8080
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://${{ secrets.ZOOP_SERVER_IP }}:8080/hc
          max-attempts: 30
          retry-delay: 5s
