name: CD on main (self-hosted)

on:
  push:
    branches:
      - main                # main 머지(푸시) 시 자동 배포

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      # 0) Docker Hub 로그인
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 1) 코드 동기화 & 컨테이너 재기동
      - name: Pull & Restart containers
        run: |
          set -e
          REPO="FC-DEV3-Final-Project/zoop-backend"
          APP_DIR="/home/ubuntu/zoop-app"
          TOKEN=${{ secrets.GH_PAT }}

          # 1-1) 코드 가져오기
          if [ ! -d "$APP_DIR/.git" ]; then
            git clone --depth 1 https://${TOKEN}@github.com/${REPO}.git "$APP_DIR"
          fi
          cd "$APP_DIR"
          git remote set-url origin https://${TOKEN}@github.com/${REPO}.git
          git fetch --tags --force
          git checkout -f main
          git pull --ff-only origin main

          # 1-2) 최신 이미지 pull
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/zoop_server:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/zoop_fastapi:latest

          # 1-3) 기존 컨테이너 종료(볼륨 유지)
          docker compose -f docker-compose.yml down --remove-orphans || true
          docker rm -f postgres-db zoop-app 2>/dev/null || true

          # 1-4) 재기동
          docker compose -f docker-compose.yml up -d --pull=never --force-recreate

      # 2) 헬스 체크
      - name: Health-check 8080
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://localhost:8080/hc       # 러너 = 서버
          max-attempts: 30
          retry-delay: 5s
