name: cd

on:
  workflow_run:
    workflows: ["Maven CI All Checks"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.ZOOP_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GH_PAT
          script: |
            set -e
            REPO="FC-DEV3-Final-Project/zoop-backend"
            APP_DIR="/home/ubuntu/zoop-app"
            TOKEN=$GH_PAT

            if [ ! -d "$APP_DIR/.git" ]; then
              git clone --depth 1 https://${TOKEN}@github.com/${REPO}.git "$APP_DIR"
            fi

            cd "$APP_DIR"
            git remote set-url origin https://${TOKEN}@github.com/${REPO}.git
            git pull --ff-only origin main

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/zoop_server:latest
            docker compose -f docker-compose.yml down --remove-orphans
            docker compose -f docker-compose.yml up -d --pull=never

      - name: Health-check 8080
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://${{ secrets.ZOOP_SERVER_IP }}:8080/hc
          max-attempts: 30
          retry-delay: 5s
