name: cd

on:
  workflow_run:
    workflows: ["Maven CI All Checks"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4      # (필요 없으면 삭제)

      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.ZOOP_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu
            # 최신 이미지 pull
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/zoop_server:latest
            # 기존 컨테이너·네트워크 정리
            sudo docker compose down
            # 새 버전 기동
            sudo docker compose up -d

      - name: Health-check 8080
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://${{ secrets.ZOOP_SERVER_IP }}:8080/hc
          max-attempts: 30
          retry-delay: 5s