name: cd

on:
  workflow_run:
    workflows: ["Maven CI All Checks"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.ZOOP_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            # 1) 첫 배포일 경우 폴더 생성 & 코드 클론
            if [ ! -d "/home/ubuntu/zoop-app" ]; then
              git clone --depth 1 https://github.com/FC-DEV3-Final-Project/zoop-backend.git /home/ubuntu/zoop-app
            fi

            cd /home/ubuntu/zoop-app

            # 2) 최신 코드 가져오기 (Compose 포함)
            git fetch --prune origin
            git reset --hard origin/main

            # 3) 최신 이미지 Pull
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/zoop_server:latest

            # 4) 컨테이너 재기동
            docker compose down --remove-orphans
            docker compose up -d --pull=never

      - name: Health-check 8080
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://${{ secrets.ZOOP_SERVER_IP }}:8080/hc
          max-attempts: 30
          retry-delay: 5s
