name: Maven CI All Checks

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Maven Wrapper에 실행 권한 부여
      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw

      # 1. 빌드 및 테스트
      - name: Build and Test
        run: ./mvnw clean verify

      # 2. 정적 분석(SpotBugs)
      - name: SpotBugs
        run: ./mvnw spotbugs:check
