name: CI
on:
  push:
    paths:
      - "backend/**"
      - "crawler/**"
jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: backend } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "21" }
      - run: ./mvnw test -B
  crawler-test:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: crawler } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: |
          pipx install poetry
          poetry install
          poetry run pytest -q
