name: Maven CI All Checks (self-hosted)

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build-and-test:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v4        # 0) 소스 가져오기

      - uses: actions/setup-java@v4      # 1) JDK 17
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/cache@v3           # 2) Maven 캐시
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # 3) 빌드·테스트
      - name: Build and Test
        run: |
          chmod +x ./mvnw          # wrapper 권한
          ./mvnw -B clean verify   # 단위·통합 테스트

      - name: SpotBugs
        run: ./mvnw -B spotbugs:check

      # 4) FastAPI 이미지 빌드·푸시
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push FastAPI Image
        env:
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/zoop_fastapi
        run: |
          set -e
          docker build --platform linux/amd64 -t $IMAGE:latest -t $IMAGE:${{ github.sha }} ./fastapi_service
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}
