jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # ↓↓↓ 기존 스텝들 그대로 ↓↓↓
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw
      - name: Build and Test
        run: ./mvnw clean verify
      - name: SpotBugs
        run: ./mvnw spotbugs:check
      # 1) **Docker Hub 로그인** (이미 있음)
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 2) **Spring 이미지 빌드·푸시** ← ★ 여기 추가 ★
      - name: Build & Push Spring Image
        run: |
          set -e
          export SPRING_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/zoop_server
          ./mvnw -q -DskipTests package          # JAR 생성
          docker build --platform linux/amd64 \
            -t $SPRING_IMAGE:latest \
            -t $SPRING_IMAGE:${{ github.sha }} .
          docker push $SPRING_IMAGE:latest
          docker push $SPRING_IMAGE:${{ github.sha }}
      # 3) **FastAPI 이미지 빌드·푸시** (기존 스텝 유지)
      - name: Build & Push FastAPI Image
        run: |
          set -e
          export FASTAPI_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/zoop_fastapi
          docker build --platform linux/amd64 \
            -t $FASTAPI_IMAGE:latest \
            -t $FASTAPI_IMAGE:${{ github.sha }} \
            ./fastapi_service
          docker push $FASTAPI_IMAGE:latest