name: Maven & Python CI

on:
  push:
  pull_request:

jobs:
  backend:
    name: Backend (Maven)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
      - name: Grant execute permission for Maven Wrapper
        run: chmod +x backend/mvnw
      - name: Build and Test
        run: ./mvnw clean verify
      - name: SpotBugs
        run: ./mvnw spotbugs:check

  crawler:
    name: Crawler (Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: crawler
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Cache Poetry & Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('crawler/pyproject.toml') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root
      - name: Run Tests
        run: poetry run pytest
      - name: Type Check
        run: poetry run mypy src/crawler
