name: Delete Merged Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/delete-branch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
